# Generated by Django 5.2.12 on 2026-03-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FortyTwoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_id', models.CharField(max_length=255, unique=True)),
                ('intra_level', models.IntegerField()),
                ('intra_wallet', models.IntegerField()),
                ('login', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('avatar_url', models.URLField(max_length=500)),
                ('coalition', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
