# Generated by Django 5.2.12 on 2026-03-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortytwoprofile',
            name='intra_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='fortytwoprofile',
            name='intra_level',
            field=models.FloatField(),
        ),
    ]
