# Generated by Django 5.2.12 on 2026-03-14 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_fortytwoprofile_intra_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fortytwoprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forty_two_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fortytwoprofile',
            name='intra_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='fortytwoprofile',
            name='intra_level',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
