# Generated by Django 5.2.12 on 2026-03-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_eval_points_field'),
        ('authentication', '0009_move_coalition_model_to_coalitions'),
    ]

    operations = [
    ]
