from django.utils.dateparse import parse_datetime


CURRENT_SEASON_START = '2026-04-08T15:42:00Z'
CURRENT_SEASON_END = '2026-10-08T10:00:00Z'
CURRENT_SEASON_START_DT = parse_datetime(CURRENT_SEASON_START)
CURRENT_SEASON_END_DT = parse_datetime(CURRENT_SEASON_END)
CURRENT_SEASON_START_DATE = CURRENT_SEASON_START_DT.date()
CURRENT_SEASON_END_DATE = CURRENT_SEASON_END_DT.date()

CURRENT_SEASON_INITIAL_COALITION_BONUS = {
	'tiamant': 3000,
	'zefiria': 3500,
	'marventis': 9500,
	'ignisaria': 4000,
}
