# Generated by Django 5.2.12 on 2026-03-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_id', models.PositiveBigIntegerField(unique=True)),
                ('user_id', models.PositiveBigIntegerField()),
                ('campus_id', models.PositiveIntegerField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('intra_id', 'campus_id')},
            },
        ),
    ]
