# Generated by Django 5.2.12 on 2026-03-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campususer',
            name='coalition_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campususer',
            name='coalition_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campususer',
            name='coalition_slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
