# Generated by Django 5.2.12 on 2026-03-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_campususer_coalition_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campususer',
            unique_together={('intra_id', 'user_id')},
        ),
        migrations.AddField(
            model_name='campususer',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='campususer',
            name='correction_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campususer',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campususer',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campususer',
            name='grade',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='campususer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campususer',
            name='level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='campususer',
            name='login',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campususer',
            name='pool_month',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='campususer',
            name='pool_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campususer',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='campususer',
            name='campus_id',
        ),
        migrations.RemoveField(
            model_name='campususer',
            name='is_primary',
        ),
    ]
