# Generated by Django 5.2.12 on 2026-03-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_alter_campususer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campususer',
            name='coalition_total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campususer',
            name='coalition_user_score',
            field=models.IntegerField(default=0),
        ),
    ]
