# Generated by Django 5.2.12 on 2026-03-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_campususer_coalition_total_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coalition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coalition_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('total_score', models.IntegerField(default=0)),
                ('leader_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
