# Generated by Django 5.2.12 on 2026-03-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_campususer_user_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campususer',
            name='level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
