# Generated by Django 5.2.12 on 2026-03-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_campususer_user_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='campususer',
            name='general_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
