# Generated by Django 5.2.12 on 2026-03-31 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0007_alter_campususer_level'),
        ('sync', '0007_campususer_general_rank'),
    ]

    operations = [
    ]
