# Generated by Django 5.2.12 on 2026-03-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0008_merge_20260331_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campususer',
            name='coalition_total_score',
        ),
        migrations.AddField(
            model_name='campususer',
            name='coalition_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
