# Generated by Django 5.2.12 on 2026-04-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0010_coalitionscoresnapshot_campususerscoresnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campususerscoresnapshot',
            new_name='sync_campus_campus__920407_idx',
            old_name='sync_campu_campus__930463_idx',
        ),
        migrations.RenameIndex(
            model_name='coalitionscoresnapshot',
            new_name='sync_coalit_coaliti_183c11_idx',
            old_name='sync_coalit_coalit_aa8c59_idx',
        ),
    ]
