# Generated by Django 5.2.12 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0011_rename_sync_campu_campus__930463_idx_sync_campus_campus__920407_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('last_time_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
