# Generated by Django 5.2.16 on 2026-07-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0015_campususer_coalitions_user_id_and_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='campususer',
            name='last_active_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
