# Generated by Django 5.2.16 on 2026-07-31 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0016_campususer_last_active_time'),
        ('sync', '0016_merge_projects_evaluations'),
    ]

    operations = [
    ]
