# Generated by Django 5.2.16 on 2026-08-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0017_merge_20260801_1015'),
        ('sync', '0017_merge_online_status_projects_evaluations'),
    ]

    operations = [
    ]
