# Generated by Django 5.2.16 on 2026-08-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0018_merge_20260801_1104'),
        ('sync', '0018_merge_20260801_1940'),
    ]

    operations = [
    ]
