# Generated by Django 5.2.17 on 2026-08-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0019_merge_20260803_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='campususer',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
