# Generated by Django 5.2.17 on 2026-08-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0020_campususer_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='campususer',
            name='today_rps_wins',
            field=models.IntegerField(default=0),
        ),
    ]
