# Generated by Django 5.2.12 on 2026-04-05 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, to='users.friendslist')),
                ('friends_requests_received', models.ManyToManyField(blank=True, related_name='friend_request_targets', to='users.friendslist')),
                ('friends_requests_sent', models.ManyToManyField(blank=True, related_name='friend_request_sources', to='users.friendslist')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friends_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
