# Generated by Django 5.2.12 on 2026-04-06 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('completionDate', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.ManyToManyField(blank=True, to='users.achievement')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
