# Generated by Django 5.2.12 on 2026-04-11 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('items_per_page', models.PositiveIntegerField(default=10)),
                ('theme_mode', models.CharField(default='dark', max_length=20)),
                ('receive_notifications', models.BooleanField(default=True)),
                ('custom_username', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
