# Generated by Copilot to separate shared achievements from per-user achievement state.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('users', '0002_achievement_achievementlist'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.RemoveField(
			model_name='achievement',
			name='completed',
		),
		migrations.RemoveField(
			model_name='achievement',
			name='completionDate',
		),
		migrations.RemoveField(
			model_name='achievement',
			name='progress',
		),
		migrations.AddField(
			model_name='achievement',
			name='slug',
			field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
		),
		migrations.CreateModel(
			name='UserAchievement',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
				('progress', models.PositiveSmallIntegerField(default=0)),
				('completed_at', models.DateTimeField(blank=True, null=True)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='users.achievement')),
				('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
			],
			options={
				'constraints': [models.UniqueConstraint(fields=('owner', 'achievement'), name='unique_user_achievement')],
			},
		),
		migrations.CreateModel(
			name='AchievementEvent',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('event_type', models.CharField(choices=[('achievement.completed', 'Achievement completed')], max_length=64)),
				('payload', models.JSONField(blank=True, default=dict)),
				('delivered_at', models.DateTimeField(blank=True, null=True)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_events', to='users.achievement')),
				('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_events', to=settings.AUTH_USER_MODEL)),
				('user_achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='users.userachievement')),
			],
		),
	]