# Generated by Django 5.2.13 on 2026-04-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='show_sensitive_data',
            field=models.BooleanField(default=True),
        ),
    ]
