# Generated by Django 5.2.16 on 2026-07-15 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0015_campususer_coalitions_user_id_and_cursor'),
        ('users', '0003_userpreferences_show_sensitive_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_HTML', models.TextField(default='<div class="inline-flex rounded-lg border border-border bg-card p-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-medal h-5 w-5 text-(--coalition-color)"><path d="M7.21 15 2.66 7.14a2 2 0 0 1 .13-2.2L4.4 2.8A2 2 0 0 1 6 2h12a2 2 0 0 1 1.6.8l1.6 2.14a2 2 0 0 1 .14 2.2L16.79 15"></path><path d="M11 12 5.12 2.2"></path><path d="m13 12 5.88-9.8"></path><path d="M8 7h8"></path><circle cx="12" cy="17" r="5"></circle><path d="M12 18v-2h-.5"></path></svg></div>')),
                ('name', models.TextField(default='Dios de las arepas')),
                ('description', models.TextField(default='Has diseñado la Arepacendence definitiva')),
                ('completion_points', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completion_date', models.DateTimeField(null=True)),
                ('achievement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.achievement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sync.campususer')),
            ],
        ),
    ]
