# Generated by Django 5.2.16 on 2026-07-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_achievement_userachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.TextField(default='Dios de las arepas', unique=True),
        ),
    ]
