# Generated by Django 5.2.16 on 2026-07-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0016_merge_projects_evaluations'),
        ('users', '0005_alter_achievement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ManyToManyField(to='sync.campususer'),
        ),
    ]
