# Generated by Django 5.2.16 on 2026-07-22 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0016_merge_projects_evaluations'),
        ('users', '0006_remove_userachievement_user_userachievement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sync.campususer'),
            preserve_default=False,
        ),
    ]
