# Generated by Django 5.2.16 on 2026-07-22 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0016_merge_projects_evaluations'),
        ('users', '0007_remove_userachievement_user_userachievement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.campususer'),
        ),
    ]
