# Generated by Django 5.2.17 on 2026-08-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userachievement_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
